#################
### AUTOSTART ###
#################

exec-once = telegram-desktop -startintray
exec-once = zen-browser
exec-once = keepassxc ~/Documents/Security/Пароли.kdbx 
exec-once = syncthing serve
exec-once = AmneziaVPN 
exec-once = udiskie
exec-once = hypridle
exec-once = $HOME/.config/hypr/scripts/change-wallpaper.sh
exec-once = wl-paste --watch clipvault store
exec-once = ssh-add ~/.ssh/id_ed25519
