#################
### AUTOSTART ###
#################

exec-once = telegram-desktop -startintray
exec-once = zen-browser
exec-once = keepassxc $HOME/Documents/Security/Passwords.kdbx 
exec-once = syncthing serve
exec-once = AmneziaVPN 
exec-once = udiskie
exec-once = hypridle
exec-once = $HOME/Scripts/commands/my-change-wallpaper
exec-once = ssh-add ~/.ssh/id_ed25519
