$font = NotoSerif Nerd Font Propo

# GENERAL
general {
  disable_loading_bar = false 
  ignore_empty_input = true
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/Wallpapers/lockScreen.png
  blur_passes = 3 
  color = $base
  blur_size = 3 
}

shape {
  monitor = 
  color = rgba(2E344033)
  position = -900, 0
  zIndex = 0
  size = 840,1440
} 

# TIME
label {
  monitor =
  text = cmd[update:30000] echo "$(date +"%R")"
  color = $text
  font_size = 90
  font_family = $font
  position = -900, 140
  # position = 220, 800
}

# DATE 
label {
  monitor = 
  text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
  color = $text
  font_size = 25
  font_family = $font
  position = -900, 60 
  # position = 180, 750
}

label {
  monitor = 
  text = cmd[update:1000] echo "$LAYOUT"
  color = $text
  font_size = 18 
  font_family = $font
  position = -660, -80
  # position = 560,620
}

input-field {
  monitor =
  size = 640, 5%
  outline_thickness = 3
  inner_color = rgba(, 0, 0, 0.0) # no fill

  outer_color = rgba(ECEFF4FF)
  check_color = rgba(EBCB8BFF)
  fail_color = rgba(BF616AFF) 

  font_color = rgb(143, 143, 143)
  fade_on_empty = false
  rounding = 15

  position = -900, -20
  halign = center
  valign = center
}
