general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
  timeout = 600
  on-timeout = hyprlock
}


listener { 
    timeout = 300 
    on-timeout = /home/nikitab/Scripts/commands/my-monitor-action  dim
    on-resume = echo "1" >> /home/nikitab/commands/my-monitor-action resume
}
