general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
  timeout = 600
  on-timeout = hyprlock
}


listener { 
    timeout = 300 
    on-timeout = /home/nikitab/Scripts/monitor.sh
    on-resume = echo "1" >> /tmp/hypridle-ddc-module-rx 
}
