windowrule {
  name = Player
  match:initial_title = Picture-in-Picture

  float = 1
  pin = 1
  content = video
  
  move = (monitor_w-window_w-68) (monitor_h-window_h-68)
  size = (monitor_w/5) (monitor_h/5)
}

windowrule {
  name = 'Games'

  content = game
  workspace = emptym
  match:initial_title = Minecraft* 1.18.2
  match:initial_title = Surviving Mars
  tile = on
}

windowrule {
  name = AmneziaVPN

  match:class = AmneziaVPN
  float = 1
  pin = 1 
  move = (monitor_w-window_w-68) 68
}

windowrule {
  name = Steam
  match:class = steam

  float = 1
  size = 400 1000
  move = (monitor_w-window_w-68) 68
}
