windowrulev2 = float, initialTitle:(Картинка в)
windowrulev2 = float, initialTitle:(Picture-in-Picture)
windowrulev2 = tile,  initialTitle:(Minecraft* 1.18.2)


windowrule = float, class:AmneziaVPN
windowrule = pin, class:AmneziaVPN
windowrule = move 100%-w-68 68, class:AmneziaVPN

