general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
  timeout = 600
  on-timeout = hyprlock
}


listener { 
    timeout = 300 
    on-timeout = $HOME/Scripts/commands/my-monitor-action dim
    on-resume = $HOME/Scripts/commands/my-monitor-action resume
}
