windowrule {
  name = Player
  match:initial_title = Picture-in-Picture

  float = 1
  pin = 1
  content = video
  
  move = (monitor_w-window_w-68) (monitor_h-window_h-68)
  size = (monitor_w/5) (monitor_h/5)
}

windowrule {
  name = 'Games'

  match:initial_title = Minecraft* 1.18.2
  match:initial_title = Surviving Mars
  match:title = New Vegas Extended Edition
  match:title = Fallout: New Vegas

  tile = on
  content = game
  workspace = emptym
}

windowrule {
  name = AmneziaVPN

  match:class = AmneziaVPN
  float = 1
  pin = 1 
  move = (monitor_w-window_w-68) 68
}

windowrule {
  name = Dowload
  match:title = Opening *

  float = 1
}

windowrule {
  name = "Test Fix"
  match:xwayland = true
  match:class = ^$
  match:title = ^$
  no_focus = on
}
