general {
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
  timeout = 600
  on-timeout = hyprlock
}


listener { 
    timeout = 300 
    on-timeout = $HOME/.dotfiles/commands/my-monitor dim
    on-resume = $HOME/.dotfiles/commands/my-monitor-resume
}
