# Move between tabs
clear_all_shortcuts no

map ctrl+shift+e open_url_with_hints
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

# Fonts
map ctrl+shift+minus change_font_size all -2.0
map ctrl+shift+plus change_font_size all +2.0

# Tabs
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# Windows
map ctrl+shift+enter new_window
map ctrl+shift+q close_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window
map ctrl+shift+f move_window_forward
map ctrl+shift+b move_window_backward
map ctrl+shift+r start_resizing_window
map ctrl+shift+1 first_window
map ctrl+shift+2 second_window
map ctrl+shift+3 third_window
map ctrl+shift+4 fourth_window
map ctrl+shift+5 fifth_window
map ctrl+shift+6 sixth_window
map ctrl+shift+7 seventh_window
map ctrl+shift+8 eighth_window
map ctrl+shift+9 ninth_window
